### ISSUE TITLE
make reference to the adaptor documentation

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/Xenon-examples#16]
at xenon/build/docs/javadoc-devel/index.html

specifically, with regard to the properties, and explain that there are different kinds of properties

**Comment by sverhoeven** [comment]
point to xenon/build/docs/javadoc/index.html or http://nlesc.github.io/Xenon/versions/1.1.0/javadoc/ . Javadoc-devel is for Xenon developers not for developers using Xenon library.

**Comment by jspaaks** [comment]
You're right of course.
