### ISSUE TITLE
add simple example of connecting to a Xenon container

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/Xenon-examples#50]
- [x] start the container(s)
- [x] ssh to it (with ssh from command line)
- [x] adapt DirectoryListing URI to list directory contents of container, both from the java command line and from within eclipse
- [ ] do stuff with torque adaptor

**Comment by sverhoeven** [comment]
To run SubmitSimpleBatchJob example against the torque container used in the Xenon integration test.

Start the torque container with it's ssh port mapped to 2222 locally.
```
docker run -d --cap-add=SYS_RESOURCE -p 2222:22 --name torque  nlesc/xenon-torque
```
The torque container has a user called `xenon` with password `javagat`.
In the example create the following credential
```
Credential cred = xenon.credentials().newPasswordCredential("ssh", "xenon", "javagat".toCharArray(), null);
```
Compile the example and run it with
```
./gradlew
java -cp build/libs/Xenon-examples-all.jar nl.esciencecenter.xenon.examples.jobs.SubmitSimpleBatchJob torque://localhost:2222

```
